export const students = [
    {
        USN: '1JS19CS186',
        name: 'Varun S Athreya',
        branch: 'CSE',
        section: 'C',
        eligible: true,
        email: '1js19cs186@jssateb.ac.in',
        password: 'asdfghjkl',
        details: {
            USN: '1JS19CS186',
            CGPA: 8.5,
            backlogs: 0,
            tenth: 8.5,
            twelth: 8.5,
            placed: false,
            package: 0,
        },
    },
    {
        USN: '1JS19CS146',
        name: 'Sandeep M',
        branch: 'CSE',
        section: 'C',
        eligible: true,
        email: '1js19cs146@jssateb.ac.in',
        password: 'asdfghjkl',
        details: {
            USN: '1JS19CS146',
            CGPA: 8.5,
            backlogs: 0,
            tenth: 8.5,
            twelth: 8.5,
            placed: true,
            package: 10,
        },
    },
    {
        USN: '1JS19CS183',
        name: 'Ullas HP',
        branch: 'CSE',
        section: 'C',
        eligible: true,
        email: '1js19cs183@jssateb.ac.in',
        password: 'asdfghjkl',
        details: {
            USN: '1JS19CS183',
            CGPA: 8.5,
            backlogs: 0,
            tenth: 8.5,
            twelth: 8.5,
            placed: false,
            package: 0,
        },
    },
    {
        USN: '1JS19CS157',
        name: 'Shithin Shetty',
        branch: 'CSE',
        section: 'C',
        eligible: true,
        email: '1js19cs157@jssateb.ac.in',
        password: 'asdfghjkl',
        details: {
            USN: '1JS19CS157',
            CGPA: 8.5,
            backlogs: 0,
            tenth: 8.5,
            twelth: 8.5,
            placed: true,
            package: 10,
        },
    },
];
